/*
 * lvgl_user_config.h
 *
 *  Created on: 10.02.2026
 *      Author: toose
 */

#ifndef MAIN_LVGL_USER_CONFIG_H_
#define MAIN_LVGL_USER_CONFIG_H_



#define ACTIVATE_BLOCK_TOP_LEFT 0  // OK
#define ACTIVATE_BLOCK_TOP_MID 0   // OK
#define ACTIVATE_BLOCK_TOP_RIGHT 0 // OK
#define ACTIVATE_BLOCK_BOT_LEFT 0  // OK
#define ACTIVATE_BLOCK_BOT_MID 1
#define ACTIVATE_BLOCK_BOT_RIGHT 0

#define ACTIVATE_ANIM_SUN_MOON 1
#define ACTIVATE_ANIM_CLOUD 1
#define ACTIVATE_ANIM_WIND 1
#define ACTIVATE_ANIM_RAIN 1
#define ACTIVATE_ANIM_SNOW 1

#define SIMULATE_ANIM_SUN 0
#define SIMULATE_ANIM_CLOUD 0
#define SIMULATE_ANIM_WIND 0
#define SIMULATE_ANIM_RAIN 0
#define SIMULATE_ANIM_SNOW 0

#define UPDATE_WEATHER_ANIM_TICKS 20

#define MAX_VALUE_CO2 2400
#define MIN_VALUE_CO2 400
#define STRING_MAX_LENGHT 20

#define DAY_START_HOUR 7
#define DAY_END_HOUR 20

#define MAX_STANDBY_TIME 3600 * 5 // tick 200mS
/////////////////////////////////////////////////////////////////////////BLOCK_TOP_LEFT
#define BLOCK_TOP_LEFT_WIDTH 250
#define BLOCK_TOP_LEFT_HEIGHT 225
#define BLOCK_TOP_LEFT_X_START 10
#define BLOCK_TOP_LEFT_Y_START 10
#define BLOCK_TOP_LEFT_ALIGN_BACKGROUND LV_ALIGN_TOP_LEFT

#define BLOCK_TOP_LEFT_Y_START_TITLE -15
#define BLOCK_TOP_LEFT_ALIGN_TITLE LV_ALIGN_TOP_MID

#define BLOCK_TOP_LEFT_WIDTH_SYMBOLS 35
#define BLOCK_TOP_LEFT_HEIGHT_SYMBOLS 35
#define BLOCK_TOP_LEFT_X_START_SYMBOLS -5
#define BLOCK_TOP_LEFT_Y_START_SYMBOLS_OFFSET 15
#define BLOCK_TOP_LEFT_Y_START_SYMBOLS_1 35
#define BLOCK_TOP_LEFT_Y_START_SYMBOLS_2                                       \
  BLOCK_TOP_LEFT_Y_START_SYMBOLS_1 + BLOCK_TOP_LEFT_HEIGHT_SYMBOLS +           \
      BLOCK_TOP_LEFT_Y_START_SYMBOLS_OFFSET
#define BLOCK_TOP_LEFT_Y_START_SYMBOLS_3                                       \
  BLOCK_TOP_LEFT_Y_START_SYMBOLS_1 + (BLOCK_TOP_LEFT_HEIGHT_SYMBOLS +          \
                                      BLOCK_TOP_LEFT_Y_START_SYMBOLS_OFFSET) * \
                                         2
#define BLOCK_TOP_LEFT_ALIGN_SYMBOLS LV_ALIGN_TOP_LEFT

#define BLOCK_TOP_LEFT_X_START_VALUES                                          \
  BLOCK_TOP_LEFT_X_START_SYMBOLS + BLOCK_TOP_LEFT_WIDTH_SYMBOLS +              \
      BLOCK_TOP_LEFT_WIDTH_SYMBOLS / 2

#define BLOCK_TOP_LEFT_Y_START_VALUE_1 BLOCK_TOP_LEFT_Y_START_SYMBOLS_1
#define BLOCK_TOP_LEFT_Y_START_VALUE_2 BLOCK_TOP_LEFT_Y_START_SYMBOLS_2
#define BLOCK_TOP_LEFT_Y_START_VALUE_3 BLOCK_TOP_LEFT_Y_START_SYMBOLS_3
#define BLOCK_TOP_LEFT_ALIGN_VALUES LV_ALIGN_TOP_LEFT

#define BLOCK_BOT_LEFT_WIDTH 250
#define BLOCK_BOT_LEFT_HEIGHT 225
#define BLOCK_BOT_LEFT_X_START 10
#define BLOCK_BOT_LEFT_Y_START -10
#define BLOCK_BOT_LEFT_ALIGN_BACKGROUND LV_ALIGN_BOTTOM_LEFT

#define BLOCK_BOT_LEFT_Y_START_TITLE -15
#define BLOCK_BOT_LEFT_ALIGN_TITLE LV_ALIGN_TOP_MID
////////////////////////////////
#define BLOCK_BOT_LEFT_WIDTH_SYMBOLS 35
#define BLOCK_BOT_LEFT_HEIGHT_SYMBOLS 35
#define BLOCK_BOT_LEFT_X_START_SYMBOLS -5
#define BLOCK_BOT_LEFT_Y_START_SYMBOLS_OFFSET 15
#define BLOCK_BOT_LEFT_Y_START_SYMBOLS_1 35
#define BLOCK_BOT_LEFT_Y_START_SYMBOLS_2                                       \
  BLOCK_BOT_LEFT_Y_START_SYMBOLS_1 + BLOCK_BOT_LEFT_HEIGHT_SYMBOLS +           \
      BLOCK_BOT_LEFT_Y_START_SYMBOLS_OFFSET
#define BLOCK_BOT_LEFT_Y_START_SYMBOLS_3                                       \
  BLOCK_BOT_LEFT_Y_START_SYMBOLS_1 + (BLOCK_BOT_LEFT_HEIGHT_SYMBOLS +          \
                                      BLOCK_BOT_LEFT_Y_START_SYMBOLS_OFFSET) * \
                                         2
#define BLOCK_BOT_LEFT_ALIGN_SYMBOLS LV_ALIGN_TOP_LEFT

#define BLOCK_BOT_LEFT_X_START_VALUES                                          \
  BLOCK_BOT_LEFT_X_START_SYMBOLS + BLOCK_BOT_LEFT_WIDTH_SYMBOLS +              \
      BLOCK_BOT_LEFT_WIDTH_SYMBOLS / 2

#define BLOCK_BOT_LEFT_Y_START_VALUE_1 BLOCK_BOT_LEFT_Y_START_SYMBOLS_1
#define BLOCK_BOT_LEFT_Y_START_VALUE_2 BLOCK_BOT_LEFT_Y_START_SYMBOLS_2
#define BLOCK_BOT_LEFT_Y_START_VALUE_3 BLOCK_BOT_LEFT_Y_START_SYMBOLS_3
#define BLOCK_BOT_LEFT_ALIGN_VALUES LV_ALIGN_TOP_LEFT
/////////////////////////////////////////////////////////////////////////BLOCK_TOP_MID
#define BLOCK_TOP_MID_WIDTH_CO2_METER 225
#define BLOCK_TOP_MID_HEIGHT_CO2_METER 225
#define BLOCK_TOP_MID_X_START 0
#define BLOCK_TOP_MID_Y_START 10
#define BLOCK_TOP_MID_Y_START_CO2_VALUE 130
#define BLOCK_TOP_MID_ALIGN_CO2_CHART LV_ALIGN_TOP_MID
#define BLOCK_TOP_MID_START_CO2_LEFT_PART 400
#define BLOCK_TOP_MID_END_CO2_LEFT_PART 800
#define BLOCK_TOP_MID_START_CO2_RIGHT_PART 2000
#define BLOCK_TOP_MID_END_CO2_RIGHT_PART 2400

/////////////////////////////////////////////////////////////////////////BLOCK_TOP_RIGHT
/// TIME
#define BLOCK_TOP_RIGHT_WIDTH 250
#define BLOCK_TOP_RIGHT_HEIGHT 225
#define BLOCK_TOP_RIGHT_X_START -10
#define BLOCK_TOP_RIGHT_Y_START 10
#define BLOCK_TOP_RIGHT_ALIGN_BACKGROUND LV_ALIGN_TOP_RIGHT

#define BLOCK_TOP_RIGHT_Y_START_TITLE -15
#define BLOCK_TOP_RIGHT_ALIGN_TITLE LV_ALIGN_TOP_MID

#define BLOCK_TOP_RIGHT_X_START_VALUES 25
#define BLOCK_TOP_RIGHT_X_START_VALUE_3 BLOCK_TOP_RIGHT_X_START_VALUES + 55
#define BLOCK_TOP_RIGHT_Y_START_VALUE_1 BLOCK_TOP_LEFT_Y_START_SYMBOLS_1 - 10
#define BLOCK_TOP_RIGHT_Y_START_VALUE_2 BLOCK_TOP_LEFT_Y_START_SYMBOLS_2 + 10
#define BLOCK_TOP_RIGHT_Y_START_VALUE_3 BLOCK_TOP_LEFT_Y_START_SYMBOLS_3 + 25
#define BLOCK_TOP_RIGHT_ALIGN_VALUES LV_ALIGN_TOP_LEFT
/////////////////////////////////////////////////////////////////////////BLOCK_BOT_MID
/// CO2 History Notifications
#define BLOCK_BOT_MID_WIDTH_CO2_CHART 250
#define BLOCK_BOT_MID_HEIGHT_CO2_CHART 120
#define BLOCK_BOT_MID_Y_START_TITLE_CO2_CHART 80
#define BLOCK_BOT_MID_ALIGN_CO2_CHART LV_ALIGN_CENTER
#define BLOCK_BOT_MID_Y_START_CO2_CHART 0

#define BLOCK_BOT_MID_WIDTH_SYMBOL 45
#define BLOCK_BOT_MID_HEIGHT_SYMBOL 45
#define BLOCK_BOT_MID_Y_START_SYMBOLS -50
#define BLOCK_BOT_MID_X_START_SYMBOL_OFFSET                                    \
  BLOCK_BOT_MID_WIDTH_SYMBOL / 2 + BLOCK_BOT_MID_WIDTH_SYMBOL
#define BLOCK_BOT_MID_X_START_SYMBOL_1 -105
#define BLOCK_BOT_MID_X_START_SYMBOL_2                                         \
  BLOCK_BOT_MID_X_START_SYMBOL_1 + BLOCK_BOT_MID_X_START_SYMBOL_OFFSET
#define BLOCK_BOT_MID_X_START_SYMBOL_3                                         \
  BLOCK_BOT_MID_X_START_SYMBOL_2 + BLOCK_BOT_MID_X_START_SYMBOL_OFFSET
#define BLOCK_BOT_MID_X_START_SYMBOL_4                                         \
  BLOCK_BOT_MID_X_START_SYMBOL_3 + BLOCK_BOT_MID_X_START_SYMBOL_OFFSET
#define BLOCK_BOT_MID_ALIGN_SYMBOL LV_ALIGN_BOTTOM_MID

#define BLOCK_BOT_MID_ALIGN_STANDBY_BAR LV_ALIGN_BOTTOM_MID
#define BLOCK_BOT_MID_Y_START_STANDBY_BAR -10
#define BLOCK_BOT_MID_WIDTH_STANDBY_BAR 250
#define BLOCK_BOT_MID_HEIGHT_STANDBY_BAR 20

#define POPUP_WINDOW_HEIGHT 400
#define POPUP_WINDOW_WIDTH 600
#define POPUP_WINDOW_ALIGN LV_ALIGN_CENTER


//#define BLOCK_BOT_MID_HEIGHT_WIFI_POPUP 400
//#define BLOCK_BOT_MID_WIDTH_WIFI_POPUP 600
//#define BLOCK_BOT_MID_ALIGN_WIFI_POPUP LV_ALIGN_CENTER
/////////////////////////////////////////////////////////////////////////BLOCK_BOT_RIGHT
///WEATHER ANIMATIONS
////////////////////COORDINATES
#define BLOCK_BOT_RIGHT_WIDTH 250
#define BLOCK_BOT_RIGHT_HEIGHT 225
#define BLOCK_BOT_RIGHT_ALIGN_BACKGROUND LV_ALIGN_BOTTOM_RIGHT
#define BLOCK_BOT_RIGHT_X_START -10
#define BLOCK_BOT_RIGHT_Y_START -10

#define BLOCK_BOT_RIGHT_ALIGN_WEATHER_ANIM LV_ALIGN_TOP_LEFT
#define BLOCK_BOT_RIGHT_X_START_WEATHER_ANIM_SUN_MOON -50
#define BLOCK_BOT_RIGHT_Y_START_WEATHER_ANIM_SUN_MOON -50

#define BLOCK_BOT_RIGHT_SPEED_WEATHER_ANIM_SUN_MOON 80000 // mS

#define BLOCK_BOT_RIGHT_MAX_WEATHER_ANIM_CLOUDS 4

#define BLOCK_BOT_RIGHT_X_START_WEATHER_ANIM_CLOUDS_BIG_110_50 40
#define BLOCK_BOT_RIGHT_Y_START_WEATHER_ANIM_CLOUDS_BIG_110_50 40
#define BLOCK_BOT_RIGHT_AMPLITUDE_WEATHER_ANIM_CLOUDS_BIG_110_50 55
#define BLOCK_BOT_RIGHT_SPEED_WEATHER_ANIM_CLOUDS_BIG_110_50 85000

#define BLOCK_BOT_RIGHT_X_START_WEATHER_ANIM_CLOUDS_MID_90_45 75
#define BLOCK_BOT_RIGHT_Y_START_WEATHER_ANIM_CLOUDS_MID_90_45 65
#define BLOCK_BOT_RIGHT_AMPLITUDE_WEATHER_ANIM_CLOUDS_MID_90_45 50
#define BLOCK_BOT_RIGHT_SPEED_WEATHER_ANIM_CLOUDS_MID_90_45 65000

#define BLOCK_BOT_RIGHT_X_START_WEATHER_ANIM_CLOUDS_SMALL_70_35 45
#define BLOCK_BOT_RIGHT_Y_START_WEATHER_ANIM_CLOUDS_SMALL_70_35 85
#define BLOCK_BOT_RIGHT_AMPLITUDE_WEATHER_ANIM_CLOUDS_SMALL_70_35 55
#define BLOCK_BOT_RIGHT_SPEED_WEATHER_ANIM_CLOUDS_SMALL_70_35 55000

#define BLOCK_BOT_RIGHT_X_START_WEATHER_ANIM_CLOUDS_THIN_80_30 60
#define BLOCK_BOT_RIGHT_Y_START_WEATHER_ANIM_CLOUDS_THIN_80_30 105
#define BLOCK_BOT_RIGHT_AMPLITUDE_WEATHER_ANIM_CLOUDS_THIN_80_30 75
#define BLOCK_BOT_RIGHT_SPEED_WEATHER_ANIM_CLOUDS_THIN_80_30 40000

#define BLOCK_BOT_RIGHT_MAX_WEATHER_ANIM_WINDS 4

#define BLOCK_BOT_RIGHT_X_START_WEATHER_ANIM_WIND_SLOW 10
#define BLOCK_BOT_RIGHT_Y_START_WEATHER_ANIM_WIND_SLOW 100
#define BLOCK_BOT_RIGHT_SPEED_WEATHER_ANIM_WIND_SLOW 60000
#define BLOCK_BOT_RIGHT_TURBULENCE_WEATHER_ANIM_WIND_SLOW 50

#define BLOCK_BOT_RIGHT_X_START_WEATHER_ANIM_WIND_MED 20
#define BLOCK_BOT_RIGHT_Y_START_WEATHER_ANIM_WIND_MED 130
#define BLOCK_BOT_RIGHT_SPEED_WEATHER_ANIM_WIND_MED 30000
#define BLOCK_BOT_RIGHT_TURBULENCE_WEATHER_ANIM_WIND_MED 60

#define BLOCK_BOT_RIGHT_X_START_WEATHER_ANIM_WIND_FAST 30
#define BLOCK_BOT_RIGHT_Y_START_WEATHER_ANIM_WIND_FAST 70
#define BLOCK_BOT_RIGHT_SPEED_WEATHER_ANIM_WIND_FAST 15000
#define BLOCK_BOT_RIGHT_TURBULENCE_WEATHER_ANIM_WIND_FAST 80

#define BLOCK_BOT_RIGHT_MAX_WEATHER_ANIM_RAINS 20
#define BLOCK_BOT_RIGHT_MAX_WEATHER_ANIM_SNOWS 20
#define BLOCK_BOT_RIGHT_MULT_FACTOR_WEATHER_ANIM_SNOWS 2
#define BLOCK_BOT_RIGHT_SPEED_WEATHER_ANIM_RAIN_SNOW 60000



#endif /* MAIN_LVGL_USER_CONFIG_H_ */
